name: Deploy to Staging
on:
  release:
    types:
      - created
jobs:
  Deploy-to-Staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Staging
      # GITHUB_REF stores the release git tag
      run: git push --force origin $GITHUB_REF:deploy-to-staging