name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  Deploy-to-Staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Staging
      # GITHUB_REF contains the git tag of the release
      run: git push --force origin $GITHUB_REF:deploy-to-staging